services:
  prcs-health-capacity:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - /opt/prcs-health/prcs-health-capacity/data:/app/data

