"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, ChartNoAxesColumnIncreasing, Check, ChevronsUpDown, CirclePlus, FileDown, Landmark, Layers3, Pencil, Settings, Stethoscope } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";

type HospitalRow={id:number;name:string};
type Administration={id:number;hospitalId:number;name:string;hospitalName:string};
type Department={id:number;hospitalId:number;administrationId:number;division:string;name:string;hospitalName:string};
type JobTitle={id:number;name:string;active:number};
type Staffing={id:number;hospitalId:number;hospitalName:string;departmentId:number;administrationId:number;division:string;departmentName:string;jobTitleId:number;jobTitle:string;required:number;available:number;gap:number};
type Data={hospitals:HospitalRow[];administrations:Administration[];departments:Department[];jobTitles:JobTitle[];staffing:Staffing[]};
type View="dashboard"|"entry"|"settings";

declare global { interface Document { modelContext?: { registerTool:(tool:unknown, options?:{signal?:AbortSignal})=>void|Promise<void> } } }

const nf=new Intl.NumberFormat("en-US");
const empty:Data={hospitals:[],administrations:[],departments:[],jobTitles:[],staffing:[]};

async function request(path:string, options?:RequestInit){
  const res=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});
  const body=await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(body.error||"تعذر حفظ البيانات");
  return body;
}

export default function Home(){
  const [data,setData]=useState<Data>(empty); const [view,setView]=useState<View>("dashboard");
  const [loading,setLoading]=useState(true); const [hospitalFilter,setHospitalFilter]=useState("all"); const [administrationFilter,setAdministrationFilter]=useState("all"); const [departmentFilter,setDepartmentFilter]=useState("all"); const [jobTitleFilter,setJobTitleFilter]=useState("all");
  const load=useCallback(async()=>{try{setLoading(true);setData(await request("/api/data"))}catch(e){toast.error(e instanceof Error?e.message:"تعذر تحميل البيانات")}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{setAdministrationFilter("all");setDepartmentFilter("all")},[hospitalFilter]);
  useEffect(()=>{setDepartmentFilter("all")},[administrationFilter]);

  const selectedAdministrations=useMemo(()=>hospitalFilter==="all"?data.administrations:data.administrations.filter(a=>a.hospitalId===Number(hospitalFilter)),[data.administrations,hospitalFilter]);
  const selectedDepartments=useMemo(()=>data.departments.filter(d=>(hospitalFilter==="all"||d.hospitalId===Number(hospitalFilter))&&(administrationFilter==="all"||d.administrationId===Number(administrationFilter))),[data.departments,hospitalFilter,administrationFilter]);
  const rows=useMemo(()=>data.staffing.filter(r=>(hospitalFilter==="all"||r.hospitalId===Number(hospitalFilter))&&(administrationFilter==="all"||r.administrationId===Number(administrationFilter))&&(departmentFilter==="all"||r.departmentId===Number(departmentFilter))&&(jobTitleFilter==="all"||r.jobTitleId===Number(jobTitleFilter))),[data.staffing,hospitalFilter,administrationFilter,departmentFilter,jobTitleFilter]);
  const totals=useMemo(()=>rows.reduce((a,r)=>({required:a.required+r.required,available:a.available+r.available,gap:a.gap+r.gap}),{required:0,available:0,gap:0}),[rows]);
  const coverage=totals.required?Math.min(100,Math.round(totals.available/totals.required*100)):0;

  useEffect(()=>{
    const context=document.modelContext;if(!context?.registerTool)return;const controller=new AbortController();
    const register=(tool:unknown)=>Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});
    register({name:"read_operational_capacity",title:"قراءة القدرة التشغيلية",description:"يعيد ملخص الاحتياج والموجود والعجز حسب المستشفى والقسم المحددين في لوحة العرض.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async()=>({required:totals.required,available:totals.available,gap:totals.gap,coverage})});
    register({name:"create_hospital",title:"إضافة مستشفى",description:"يضيف مستشفى جديدًا إلى نظام القدرة التشغيلية.",inputSchema:{type:"object",properties:{name:{type:"string",minLength:2}},required:["name"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const name=(input as {name?:string})?.name?.trim();if(!name||name.length<2)throw new Error("اسم المستشفى مطلوب");const result=await request("/api/hospitals",{method:"POST",body:JSON.stringify({name})});await load();return result}});
    register({name:"update_staffing_record",title:"تعديل سجل وظيفي",description:"يعدل المسمى والاحتياج والموجود لسجل وظيفي موجود ويعيد احتساب العجز.",inputSchema:{type:"object",properties:{id:{type:"integer",minimum:1},jobTitle:{type:"string",minLength:2},required:{type:"integer",minimum:0},available:{type:"integer",minimum:0}},required:["id","jobTitle","required","available"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const v=input as {id:number;jobTitle:string;required:number;available:number};if(!Number.isInteger(v.id)||v.id<1||!v.jobTitle?.trim()||!Number.isInteger(v.required)||v.required<0||!Number.isInteger(v.available)||v.available<0)throw new Error("بيانات التعديل غير صحيحة");const result=await request(`/api/staffing/${v.id}`,{method:"PATCH",body:JSON.stringify(v)});await load();return result}});
    return()=>controller.abort();
  },[coverage,load,totals.available,totals.gap,totals.required]);

  return <main className="min-h-screen bg-[#f3f6f8] text-[#17212b]" dir="rtl">
    <header className="border-b border-white/10 bg-[linear-gradient(110deg,#720b1c,#b5122b)] text-white">
      <div className="mx-auto flex max-w-[1500px] items-center justify-between gap-5 px-5 py-5 lg:px-10">
        <div className="flex items-center gap-3"><span className="grid size-14 place-items-center overflow-hidden rounded-full bg-white p-1 shadow-sm"><img src="/prcs-logo.png" alt="شعار جمعية الهلال الأحمر الفلسطيني" className="size-full object-contain"/></span><div className="text-right"><h1 className="text-xl font-bold">القدرة التشغيلية لقطاع الصحة</h1><p className="mt-1 text-sm text-rose-100">جمعية الهلال الأحمر الفلسطيني</p></div></div>
        <div className="hidden rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm md:block">إدارة الاحتياج والقوة المتاحة</div>
      </div>
    </header>
    <div className="mx-auto grid max-w-[1500px] gap-6 px-4 py-6 lg:grid-cols-[220px_1fr] lg:px-10">
      <aside className="h-fit rounded-2xl border border-[#dfe5e9] bg-white p-3 shadow-sm">
        <p className="px-3 pb-2 pt-1 text-xs font-bold text-[#7a858f]">القائمة الرئيسية</p>
        <NavButton active={view==="dashboard"} onClick={()=>setView("dashboard")} icon={<ChartNoAxesColumnIncreasing/>}>لوحة العرض</NavButton>
        <NavButton active={view==="entry"} onClick={()=>setView("entry")} icon={<CirclePlus/>}>إدخال البيانات</NavButton>
        <NavButton active={view==="settings"} onClick={()=>setView("settings")} icon={<Settings/>}>الإعدادات</NavButton>
        <div className="mx-3 mt-5 border-t border-[#e7ebee] pt-4 text-xs leading-6 text-[#7a858f]">تُدار المراكز والإدارات والأقسام والمسميات الثابتة من الإعدادات.</div>
      </aside>
      <section className="min-w-0">{view==="dashboard"?<Dashboard loading={loading} data={data} rows={rows} totals={totals} coverage={coverage} hospitalFilter={hospitalFilter} setHospitalFilter={setHospitalFilter} administrationFilter={administrationFilter} setAdministrationFilter={setAdministrationFilter} departmentFilter={departmentFilter} setDepartmentFilter={setDepartmentFilter} jobTitleFilter={jobTitleFilter} setJobTitleFilter={setJobTitleFilter} administrations={selectedAdministrations} departments={selectedDepartments} reload={load}/>:view==="entry"?<EntryForms data={data} reload={load}/>:<SettingsView data={data} reload={load}/>}</section>
    </div><Toaster position="top-center" richColors />
  </main>
}

function NavButton({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button onClick={onClick} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-right text-sm font-semibold transition ${active?"bg-[#fbecef] text-[#a50f27]":"text-[#52606c] hover:bg-[#f4f6f7]"}`}><span className="[&_svg]:size-5">{icon}</span>{children}</button>}

function Dashboard({loading,data,rows,totals,coverage,hospitalFilter,setHospitalFilter,administrationFilter,setAdministrationFilter,departmentFilter,setDepartmentFilter,jobTitleFilter,setJobTitleFilter,administrations,departments,reload}:{loading:boolean;data:Data;rows:Staffing[];totals:{required:number;available:number;gap:number};coverage:number;hospitalFilter:string;setHospitalFilter:(v:string)=>void;administrationFilter:string;setAdministrationFilter:(v:string)=>void;departmentFilter:string;setDepartmentFilter:(v:string)=>void;jobTitleFilter:string;setJobTitleFilter:(v:string)=>void;administrations:Administration[];departments:Department[];reload:()=>Promise<void>}){
  const hospitalName=hospitalFilter==='all'?'كل المراكز والمنشآت':data.hospitals.find(h=>String(h.id)===hospitalFilter)?.name||'كل المراكز والمنشآت';
  const administrationName=administrationFilter==='all'?'كل الإدارات الرئيسية':data.administrations.find(a=>String(a.id)===administrationFilter)?.name||'كل الإدارات الرئيسية';
  const departmentName=departmentFilter==='all'?'كل الأقسام':data.departments.find(d=>String(d.id)===departmentFilter)?.name||'كل الأقسام';
  const jobTitleName=jobTitleFilter==='all'?'كل المسميات الوظيفية':data.jobTitles.find(j=>String(j.id)===jobTitleFilter)?.name||'كل المسميات الوظيفية';
  function exportPdf(){
    const report=window.open('','_blank','width=900,height=720');if(!report){toast.error('تعذر فتح نافذة التصدير');return}
    report.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تقرير القدرة التشغيلية</title><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;color:#17212b;margin:0;text-align:right}.head{display:flex;align-items:center;gap:18px;border-bottom:3px solid #b5122b;padding-bottom:16px}.head img{width:82px;height:82px;object-fit:contain}.head h1{margin:0 0 7px;font-size:22px}.head p{margin:0;color:#66717f}.selection{margin:22px 0;background:#f3f6f8;border:1px solid #dfe5e9;border-radius:10px;padding:14px 18px;line-height:2}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{border:1px solid #dfe5e9;border-right:5px solid #b5122b;border-radius:10px;padding:18px}.label{color:#66717f;font-size:14px}.value{font-size:30px;font-weight:800;margin-top:8px;direction:ltr;text-align:right}.foot{margin-top:28px;padding-top:12px;border-top:1px solid #dfe5e9;color:#7a858f;font-size:12px}@media print{button{display:none}}</style></head><body><header class="head"><img src="${window.location.origin}/prcs-logo.png"><div><h1>تقرير القدرة التشغيلية لقطاع الصحة</h1><p>جمعية الهلال الأحمر الفلسطيني</p></div></header><section class="selection"><div><strong>المركز / المنشأة:</strong> ${hospitalName}</div><div><strong>الإدارة الرئيسية:</strong> ${administrationName}</div><div><strong>القسم:</strong> ${departmentName}</div><div><strong>المسمى الوظيفي:</strong> ${jobTitleName}</div></section><section class="grid"><div class="card"><div class="label">إجمالي الاحتياج</div><div class="value">${nf.format(totals.required)}</div></div><div class="card"><div class="label">إجمالي الموجود</div><div class="value">${nf.format(totals.available)}</div></div><div class="card"><div class="label">إجمالي العجز</div><div class="value">${nf.format(totals.gap)}</div></div><div class="card"><div class="label">نسبة التغطية</div><div class="value">${coverage}%</div></div></section><div class="foot">تاريخ التقرير: ${new Intl.DateTimeFormat('en-GB').format(new Date())}</div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);report.document.close();
  }
  return <><div className="mb-5 flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center"><div className="text-right"><h2 className="text-2xl font-bold">لوحة القدرة التشغيلية</h2><p className="mt-1 text-sm text-[#6b7681]">اختر المستشفى والقسم لعرض الاحتياج والموجود والوظائف التي تعاني عجزًا.</p></div><Button onClick={exportPdf} variant="outline" className="h-10 border-[#b5122b] text-[#a50f27] hover:bg-[#fbecef]"><FileDown/>تصدير المؤشرات PDF</Button></div>
    <div className="mb-5 grid gap-3 rounded-2xl border border-[#dfe5e9] bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-4">
      <SearchableFilter value={hospitalFilter} onValueChange={setHospitalFilter} placeholder="كل المراكز والمنشآت" searchPlaceholder="ابحث عن مركز أو منشأة" options={[{value:"all",label:"كل المراكز والمنشآت"},...data.hospitals.map(h=>({value:String(h.id),label:h.name}))]}/>
      <SearchableFilter value={administrationFilter} onValueChange={setAdministrationFilter} placeholder="كل الإدارات الرئيسية" searchPlaceholder="ابحث عن إدارة رئيسية" options={[{value:"all",label:"كل الإدارات الرئيسية"},...administrations.map(a=>({value:String(a.id),label:a.name}))]}/>
      <SearchableFilter value={departmentFilter} onValueChange={setDepartmentFilter} placeholder="كل الأقسام" searchPlaceholder="ابحث عن قسم" options={[{value:"all",label:"كل الأقسام"},...departments.map(d=>({value:String(d.id),label:d.name}))]}/>
      <SearchableFilter value={jobTitleFilter} onValueChange={setJobTitleFilter} placeholder="كل المسميات الوظيفية" searchPlaceholder="ابحث عن مسمى وظيفي" options={[{value:"all",label:"كل المسميات الوظيفية"},...data.jobTitles.filter(j=>j.active).map(j=>({value:String(j.id),label:j.name}))]}/>
    </div>
    <div className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric title="إجمالي الاحتياج" value={totals.required} note="العدد المطلوب للتشغيل" color="#176b87"/><Metric title="إجمالي الموجود" value={totals.available} note="القوة المتاحة حاليًا" color="#18794e"/><Metric title="إجمالي العجز" value={totals.gap} note="مجموع العجز في الوظائف" color="#b5122b"/><Metric title="نسبة التغطية" value={`${coverage}%`} note="الموجود من إجمالي الاحتياج" color="#c77d10"/></div>
    <div className="overflow-hidden rounded-2xl border border-[#dfe5e9] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#e7ebee] px-5 py-4"><div><h3 className="font-bold">تفاصيل الوظائف</h3><p className="mt-1 text-xs text-[#78838d]">السجلات ذات العجز مميزة باللون الأحمر ويمكن تعديل أي سجل.</p></div><span className="rounded-full bg-[#fbecef] px-3 py-1 text-sm font-bold text-[#a50f27]">{nf.format(rows.filter(r=>r.gap>0).length)} وظيفة بعجز</span></div>
      {loading?<div className="p-10 text-center text-[#78838d]">جاري تحميل البيانات...</div>:rows.length===0?<EmptyState hasHospitals={data.hospitals.length>0}/>:<Table><TableHeader><TableRow><TableHead className="text-right">المركز / المنشأة</TableHead><TableHead className="text-right">الإدارة الرئيسية</TableHead><TableHead className="text-right">القسم</TableHead><TableHead className="text-right">الوظيفة</TableHead><TableHead className="text-center">الاحتياج</TableHead><TableHead className="text-center">الموجود</TableHead><TableHead className="text-center">العجز</TableHead><TableHead className="text-center">تعديل</TableHead></TableRow></TableHeader><TableBody>{[...rows].sort((a,b)=>b.gap-a.gap).map(r=><TableRow key={r.id} className={r.gap>0?'bg-[#fffafb]':''}><TableCell className="font-medium">{r.hospitalName}</TableCell><TableCell>{r.division}</TableCell><TableCell>{r.departmentName}</TableCell><TableCell>{r.jobTitle}</TableCell><TableCell className="text-center">{nf.format(r.required)}</TableCell><TableCell className="text-center">{nf.format(r.available)}</TableCell><TableCell className="text-center"><span className={`inline-flex min-w-9 justify-center rounded-lg px-2 py-1 font-bold ${r.gap>0?'bg-[#fbecef] text-[#a50f27]':'bg-[#eaf6ef] text-[#18794e]'}`}>{nf.format(r.gap)}</span></TableCell><TableCell className="text-center"><EditRecordDialog row={r} jobTitles={data.jobTitles} reload={reload}/></TableCell></TableRow>)}</TableBody></Table>}</div>
  </>
}

function EntryForms({data,reload}:{data:Data;reload:()=>Promise<void>}){
  const [staffHospital,setStaffHospital]=useState("");const [staffAdministration,setStaffAdministration]=useState("");const [staffDepartment,setStaffDepartment]=useState("");const [jobTitleId,setJobTitleId]=useState("");const [required,setRequired]=useState("");const [available,setAvailable]=useState("");const [busy,setBusy]=useState(false);
  const administrations=data.administrations.filter(a=>a.hospitalId===Number(staffHospital));const departments=data.departments.filter(d=>d.administrationId===Number(staffAdministration));const gap=Math.max(Number(required||0)-Number(available||0),0);
  async function submit(e:FormEvent,action:()=>Promise<void>){e.preventDefault();try{setBusy(true);await action();await reload();toast.success("تم حفظ البيانات بنجاح")}catch(err){toast.error(err instanceof Error?err.message:"تعذر الحفظ")}finally{setBusy(false)}}
  return <><div className="mb-5"><h2 className="text-2xl font-bold">إدخال الاحتياج</h2><p className="mt-1 text-sm text-[#6b7681]">اختر البيانات المعتمدة من الإعدادات ثم أدخل الاحتياج والموجود.</p></div><div className="mx-auto max-w-3xl"><FormCard icon={<Stethoscope/>} step="1" title="إضافة احتياج وظيفي" description="المسمى الوظيفي يُختار من القائمة الثابتة لمنع التكرار والاختلاف."><form onSubmit={e=>submit(e,async()=>{await request('/api/staffing',{method:'POST',body:JSON.stringify({departmentId:Number(staffDepartment),jobTitleId:Number(jobTitleId),required:Number(required),available:Number(available)})});setJobTitleId('');setRequired('');setAvailable('')})} className="grid gap-4 md:grid-cols-2"><LabeledSelect label="المركز / المنشأة" value={staffHospital} onChange={v=>{setStaffHospital(v);setStaffAdministration('');setStaffDepartment('')}} placeholder="اختر المركز" items={data.hospitals}/><LabeledSelect label="الإدارة الرئيسية" value={staffAdministration} onChange={v=>{setStaffAdministration(v);setStaffDepartment('')}} placeholder="اختر الإدارة" items={administrations}/><LabeledSelect label="القسم" value={staffDepartment} onChange={setStaffDepartment} placeholder="اختر القسم" items={departments}/><LabeledSelect label="المسمى الوظيفي الثابت" value={jobTitleId} onChange={setJobTitleId} placeholder="اختر المسمى" items={data.jobTitles.filter(j=>j.active)}/><LabeledInput label="الاحتياج" value={required} onChange={setRequired} type="number" min="0"/><LabeledInput label="الموجود" value={available} onChange={setAvailable} type="number" min="0"/><div className="md:col-span-2 flex items-center justify-between rounded-xl bg-[#f7f9fa] px-4 py-3 text-sm"><span className="text-[#65717c]">العجز المحتسب تلقائيًا</span><strong className={gap>0?'text-[#a50f27]':'text-[#18794e]'}>{nf.format(gap)}</strong></div><Button disabled={busy||!staffDepartment||!jobTitleId||required===''||available===''} className="md:col-span-2 w-full bg-[#a50f27] hover:bg-[#820b1e]">حفظ الاحتياج</Button></form></FormCard></div></>
}

function SettingsView({data,reload}:{data:Data;reload:()=>Promise<void>}){
  const [center,setCenter]=useState(""),[adminCenter,setAdminCenter]=useState(""),[admin,setAdmin]=useState(""),[depAdmin,setDepAdmin]=useState(""),[dep,setDep]=useState(""),[title,setTitle]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent,action:()=>Promise<void>,clear:()=>void){e.preventDefault();try{setBusy(true);await action();clear();await reload();toast.success("تم الحفظ بنجاح")}catch(err){toast.error(err instanceof Error?err.message:"تعذر الحفظ")}finally{setBusy(false)}}
  return <><div className="mb-5"><h2 className="text-2xl font-bold">الإعدادات</h2><p className="mt-1 text-sm text-[#6b7681]">أضف الهيكل التنظيمي بالتسلسل وثبّت المسميات الوظيفية للاستخدام في جميع السجلات.</p></div><div className="grid gap-5 xl:grid-cols-2">
    <FormCard icon={<Building2/>} step="1" title="المراكز والمنشآت" description="المستشفيات والمراكز الصحية التابعة للجمعية."><form onSubmit={e=>submit(e,()=>request('/api/hospitals',{method:'POST',body:JSON.stringify({name:center})}),()=>setCenter(''))} className="flex gap-2"><Input value={center} onChange={e=>setCenter(e.target.value)} placeholder="اسم المركز أو المنشأة"/><Button disabled={busy||center.trim().length<2}>إضافة</Button></form><RecordList items={data.hospitals} endpoint="/api/hospitals" reload={reload}/></FormCard>
    <FormCard icon={<Landmark/>} step="2" title="الإدارات الرئيسية" description="كل إدارة رئيسية مرتبطة بمركز أو منشأة."><form onSubmit={e=>submit(e,()=>request('/api/administrations',{method:'POST',body:JSON.stringify({hospitalId:Number(adminCenter),name:admin})}),()=>setAdmin(''))} className="space-y-3"><LabeledSelect label="المركز / المنشأة" value={adminCenter} onChange={setAdminCenter} placeholder="اختر المركز" items={data.hospitals}/><div className="flex gap-2"><Input value={admin} onChange={e=>setAdmin(e.target.value)} placeholder="اسم الإدارة الرئيسية"/><Button disabled={busy||!adminCenter||admin.trim().length<2}>إضافة</Button></div></form><RecordList items={data.administrations.map(a=>({...a,sub:a.hospitalName}))} endpoint="/api/administrations" reload={reload}/></FormCard>
    <FormCard icon={<Layers3/>} step="3" title="الأقسام" description="كل قسم مرتبط بإدارة رئيسية محددة."><form onSubmit={e=>submit(e,()=>request('/api/departments',{method:'POST',body:JSON.stringify({administrationId:Number(depAdmin),name:dep})}),()=>setDep(''))} className="space-y-3"><LabeledSelect label="الإدارة الرئيسية" value={depAdmin} onChange={setDepAdmin} placeholder="اختر الإدارة" items={data.administrations.map(a=>({...a,name:`${a.name} — ${a.hospitalName}`}))}/><div className="flex gap-2"><Input value={dep} onChange={e=>setDep(e.target.value)} placeholder="اسم القسم"/><Button disabled={busy||!depAdmin||dep.trim().length<2}>إضافة</Button></div></form><RecordList items={data.departments.map(d=>({...d,sub:`${d.division} — ${d.hospitalName}`}))} endpoint="/api/departments" reload={reload}/></FormCard>
    <FormCard icon={<Stethoscope/>} step="4" title="المسميات الوظيفية الثابتة" description="تظهر هذه المسميات كقائمة اختيار ولا يمكن إدخال مسمى حر."><form onSubmit={e=>submit(e,()=>request('/api/job-titles',{method:'POST',body:JSON.stringify({name:title})}),()=>setTitle(''))} className="flex gap-2"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="المسمى الوظيفي المعتمد"/><Button disabled={busy||title.trim().length<2}>إضافة</Button></form><RecordList items={data.jobTitles} endpoint="/api/job-titles" reload={reload}/></FormCard>
  </div></>
}

function RecordList({items,endpoint,reload}:{items:{id:number;name:string;sub?:string}[];endpoint:string;reload:()=>Promise<void>}){return <div className="mt-4 max-h-52 space-y-2 overflow-auto">{items.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl bg-[#f7f9fa] px-3 py-2 text-sm"><div><strong>{item.name}</strong>{item.sub&&<p className="mt-1 text-xs text-[#7a858f]">{item.sub}</p>}</div><EditNameDialog item={item} endpoint={endpoint} reload={reload}/></div>)}</div>}
function EditNameDialog({item,endpoint,reload}:{item:{id:number;name:string};endpoint:string;reload:()=>Promise<void>}){const [open,setOpen]=useState(false),[name,setName]=useState(item.name),[busy,setBusy]=useState(false);async function save(e:FormEvent){e.preventDefault();try{setBusy(true);await request(`${endpoint}/${item.id}`,{method:'PATCH',body:JSON.stringify({name})});await reload();setOpen(false);toast.success("تم تعديل السجل")}catch(err){toast.error(err instanceof Error?err.message:"تعذر التعديل")}finally{setBusy(false)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`تعديل ${item.name}`}><Pencil/></Button></DialogTrigger><DialogContent dir="rtl" className="sm:max-w-md"><DialogHeader className="text-right"><DialogTitle>تعديل السجل</DialogTitle><DialogDescription>سيظهر الاسم الجديد في جميع القوائم المرتبطة.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><LabeledInput label="الاسم" value={name} onChange={setName}/><Button disabled={busy||name.trim().length<2} className="w-full">حفظ التعديل</Button></form></DialogContent></Dialog>}

function Metric({title,value,note,color}:{title:string;value:number|string;note:string;color:string}){return <article className="relative overflow-hidden rounded-2xl border border-[#dfe5e9] bg-white p-5 shadow-sm before:absolute before:inset-y-0 before:right-0 before:w-1 before:bg-[var(--metric)]" style={{"--metric":color} as React.CSSProperties}><p className="text-sm text-[#69747e]">{title}</p><p className="mt-2 text-3xl font-black">{typeof value==='number'?nf.format(value):value}</p><p className="mt-2 text-xs text-[#8a949d]">{note}</p></article>}
function FormCard({icon,step,title,description,children}:{icon:React.ReactNode;step:string;title:string;description:string;children:React.ReactNode}){return <article className="rounded-2xl border border-[#dfe5e9] bg-white p-5 shadow-sm"><div className="mb-5 flex items-start justify-between"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#fbecef] text-[#a50f27] [&_svg]:size-5">{icon}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-[#7a858f]">{description}</p></div></div><span className="grid size-7 place-items-center rounded-full bg-[#17212b] text-xs font-bold text-white">{step}</span></div>{children}</article>}
function LabeledInput({label,value,onChange,placeholder,type='text',min}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string;min?:string}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} type={type} min={min} className="h-11"/></label>}
function LabeledSelect({label,value,onChange,placeholder,items}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;items:{id:number;name:string}[]}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="h-11 w-full"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.id} value={String(i.id)}>{i.name}</SelectItem>)}</SelectContent></Select></label>}
function SearchableFilter({value,onValueChange,placeholder,searchPlaceholder,options}:{value:string;onValueChange:(v:string)=>void;placeholder:string;searchPlaceholder:string;options:{value:string;label:string}[]}){
  const [open,setOpen]=useState(false);const selected=options.find(o=>o.value===value);
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button variant="outline" role="combobox" aria-expanded={open} className="h-11 w-full justify-between bg-white px-3 font-normal"><span className="truncate">{selected?.label||placeholder}</span><ChevronsUpDown className="size-4 shrink-0 opacity-50"/></Button></PopoverTrigger><PopoverContent align="start" className="w-[var(--radix-popover-trigger-width)] p-0"><Command dir="rtl"><CommandInput placeholder={searchPlaceholder}/><CommandList><CommandEmpty>لا توجد نتيجة مطابقة.</CommandEmpty><CommandGroup>{options.map(o=><CommandItem key={o.value} value={o.label} onSelect={()=>{onValueChange(o.value);setOpen(false)}} className="justify-between"><span>{o.label}</span><Check className={`size-4 ${value===o.value?'opacity-100':'opacity-0'}`}/></CommandItem>)}</CommandGroup></CommandList></Command></PopoverContent></Popover>
}
function EditRecordDialog({row,jobTitles,reload}:{row:Staffing;jobTitles:JobTitle[];reload:()=>Promise<void>}){
  const [open,setOpen]=useState(false);const [jobTitleId,setJobTitleId]=useState(String(row.jobTitleId));const [required,setRequired]=useState(String(row.required));const [available,setAvailable]=useState(String(row.available));const [busy,setBusy]=useState(false);
  const gap=Math.max(Number(required||0)-Number(available||0),0);
  async function save(e:FormEvent){e.preventDefault();try{setBusy(true);await request(`/api/staffing/${row.id}`,{method:'PATCH',body:JSON.stringify({jobTitleId:Number(jobTitleId),required:Number(required),available:Number(available)})});await reload();toast.success("تم تعديل السجل وإعادة احتساب العجز");setOpen(false)}catch(error){toast.error(error instanceof Error?error.message:"تعذر تعديل السجل")}finally{setBusy(false)}}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" size="icon-sm" aria-label={`تعديل ${row.jobTitle}`}><Pencil/></Button></DialogTrigger><DialogContent dir="rtl" className="sm:max-w-md"><DialogHeader className="text-right"><DialogTitle>تعديل السجل</DialogTitle><DialogDescription>{row.hospitalName} · {row.division} · {row.departmentName}</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><LabeledSelect label="المسمى الوظيفي الثابت" value={jobTitleId} onChange={setJobTitleId} placeholder="اختر المسمى" items={jobTitles.filter(j=>j.active)}/><div className="grid grid-cols-2 gap-3"><LabeledInput label="الاحتياج" value={required} onChange={setRequired} type="number" min="0"/><LabeledInput label="الموجود" value={available} onChange={setAvailable} type="number" min="0"/></div><div className="flex items-center justify-between rounded-xl bg-[#f7f9fa] px-4 py-3 text-sm"><span>العجز بعد التعديل</span><strong className={gap>0?'text-[#a50f27]':'text-[#18794e]'}>{nf.format(gap)}</strong></div><Button disabled={busy||!jobTitleId||required===''||available===''} className="w-full bg-[#a50f27] hover:bg-[#820b1e]">حفظ التعديلات</Button></form></DialogContent></Dialog>
}
function EmptyState({hasHospitals}:{hasHospitals:boolean}){return <div className="px-5 py-16 text-center"><Building2 className="mx-auto mb-3 size-10 text-[#b8c0c6]"/><h4 className="font-bold">{hasHospitals?'لا توجد سجلات ضمن الاختيار الحالي':'لا توجد بيانات بعد'}</h4><p className="mt-2 text-sm text-[#7a858f]">{hasHospitals?'جرّب تغيير الفلاتر أو أضف وظائف لهذا القسم.':'انتقل إلى إدخال البيانات وأضف المستشفى والقسم والوظائف.'}</p></div>}
